---
commands:
  full:
    exec: "bundle exec rake full"
    desc: "execute all tests"
    dependencies:
      - "bundle install --deployment"
  default:
    exec: "bundle exec rake full"
    desc: "execute all tests. If no subcommand is specific, default command will be executed"
    dependencies:
      - "bundle install --deployment"
  bvt:
    exec: "bundle exec rake tests"
    desc: "execute all core tests. It will be finished in shorter time frame"
    dependencies:
      - "bundle install --deployment"

results: ./reports
