---
suites:
  yeti:
    location: USER_INPUT
    mandatory: false
  bizops:
    location: USER_INPUT
    mendatory: false
commands:
  help:
    usage: help
    desc: list all avaiable commands
  tests:
    usage: tests
    desc: run default multiple test suites.
  aliases:
    usage: aliases
    desc: Show the list of available command aliases
  add alias:
    usage: add alias <name> <commands>
    desc: organize multiple tests under one alias
  delete alias:
    usage: delete alias <name>
    desc: remove alias
  configure yeti:
    usage: configure yeti
    desc: ! 'configure test suite: yeti before running it'
  yeti:
    usage: yeti [subcommand]
    desc: ! 'run default test for test suite: yeti, if no subcommand is specified'
  list yeti:
    usage: list yeti
    desc: ! 'list all available subcommands for test suite: yeti'
  configure bizops:
    usage: configure bizops
    desc: ! 'configure test suite: bizops before running it'
  bizops:
    usage: bizops [subcommand]
    desc: ! 'run default test for test suite: bizops, if no subcommand is specified'
  list bizops:
    usage: list bizops
    desc: ! 'list all available subcommands for test suite: bizops'
