
commands:
  yeti:
    location: "<yeti source path>"
    usage: "yeti"
    desc: "list all commands to test cloudfoundry functionalities"
    mandatory:
      list: "rake"
      result: "<result file path>"
  bizops:
    location: "<bizops source path>"
    usage: "bizops"
    desc: "list all commands to test bizops functionalities"
    mandatory:
      list: "rake"
      result: "<result file path>"
  tests:
    usage: "tests"
    desc: "it is default multiple testing command, it will run yeti and bizops test suite together"
    commands:
      - "yeti rake full[16]"
      - "bizops rake tests"
  help:
    usage: "help"
    desc: "list all avaiable commands"
  aliases:
    usage: "aliases"
    desc: "Show the list of available command aliases"
  "add alias":
    usage: "add alias <name> <commands>"
    desc: "organize multiple tests under one alias"
  "delete alias":
    usage: "delete alias <name>"
    desc: "remove alias"


